version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: Perform test
          command: |
            . venv/bin/activate
            cd tests
            pytest test_bbc_app.py
            pytest test_bbc_app_multi_core.py
            pytest test_bbc_app_multi_core_many_transactions.py
            pytest test_bbc_app_multi_core_notification_with_cancelation.py
            pytest test_bbc_app_multi_core_notification_with_disconnection.py
            pytest test_bbc_app_multiclient.py
            pytest test_bbc_app_multiclient_traverse.py
            pytest test_bbc_app_admin_tools.py
            pytest test_bbc_app_multi_core_compromising_data.py
            pytest test_bbc_app_multi_core_anycast.py
            pytest test_domain_info_adv.py
            pytest test_fileproof_multi_core.py
            pytest test_bbc_config.py
            pytest test_user_message_routing.py
            pytest test_bbc_core.py
            pytest test_bbc_network.py
            pytest test_bbc_network_encryption.py
            pytest test_data_handler_sqlite.py
            pytest test_key_exchange_manager.py
            pytest test_pending_request.py
            pytest test_bbc_ping.py
            pytest test_bbc_stats.py
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: verify version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: deploy in PyPI
          command: |
            . venv/bin/activate
            pip install wheel twine
            rm -rf dist/ bbc1.egg-info/
            python setup.py sdist
            python setup.py bdist_wheel
            twine upload --repository pypi dist/*
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
