# for alpine
#FROM sickp/alpine-sshd:latest
# for ubuntu
FROM ubuntu:latest

LABEL maintainer "Michihito Kato <mkato@zettant.com>"

ENV PASSWORD=bbc1 PYTHONIOENCODING="utf-8"

ENV SHARE_DIR=/root/.bbc1 VENV_DIR=/root/.pythonenv

VOLUME ${SHARE_DIR}
EXPOSE 22 9000 6641

ADD requirements.txt /tmp/
ADD entrypoint.sh /
WORKDIR /root/

# for apline
#RUN apk --update --no-cache add openrc bash openssh sudo g++ git tzdata musl-dev linux-headers python3 python3-dev zlib-dev libjpeg-turbo-dev libffi-dev openssl-dev && python3 -m ensurepip
# for ubuntu
RUN apt-get update && apt-get install -y git tzdata openssh-server python3 python3-dev python3-venv libffi-dev net-tools autoconf automake libtool libssl-dev make

RUN mkdir -p ${SHARE_DIR} && echo "root:${PASSWORD}" | chpasswd

# for ubuntu
RUN sed -i 's/prohibit-password/yes/' /etc/ssh/sshd_config

RUN /bin/bash -c "python3 -m venv ${VENV_DIR} && source ${VENV_DIR}/bin/activate && pip install --upgrade pip setuptools && pip install wheel && pip install -r /tmp/requirements.txt && rm -r ~/.cache && deactivate && echo \"source ${VENV_DIR}/bin/activate\" >> /root/.bashrc"

RUN mkdir -p ${SHARE_DIR}

ADD bbc1.tar.gz /root/bbc1/

WORKDIR /root/bbc1/bbc1/

RUN sh prepare.sh

CMD bash /entrypoint.sh
